---

- hosts: localhost
  tasks:
    - name: Parse Terraform Context
      set_fact:
        context: "{{ lookup('env', 'TERRAFORM_PARAMETERS_B64') | b64decode | from_json }}"

        github_template_token: "{{ lookup('env', 'GITHUB_TEMPLATE_TOKEN') }}"
        github_demo_token: "{{ lookup('env', 'GITHUB_DEMO_TOKEN') }}"

        template_auth_header: "{{ lookup('env', 'GITHUB_AUTH_TEMPLATE_HEADER') }}"
        demo_auth_header: "{{ lookup('env', 'GITHUB_AUTH_DEMO_HEADER') }}"

    - name: Validate Context
      assert:
        that:
          - context is defined
          - context.github_context is defined

          - context.github_context.target_repository is defined
          - context.github_context.target_repository.owner is defined
          - context.github_context.target_repository.repo is defined

          - github_template_token is defined
          - github_demo_token is defined

    - name: Set Repository URLs
      set_fact:
        template_repository_url_with_token: https://x-access-token:{{ github_template_token }}@github.com/{{ context.github_context.template_repository.owner }}/{{ context.github_context.template_repository.repo }}
        template_repository_url: https://github.com/{{ context.github_context.template_repository.owner }}/{{ context.github_context.template_repository.repo }}.git
        target_repository_url_with_token: https://x-access-token:{{ github_demo_token }}@github.com/{{ context.github_context.target_repository.owner }}/{{ context.github_context.target_repository.repo }}
        target_repository_url: https://github.com/{{ context.github_context.target_repository.owner }}/{{ context.github_context.target_repository.repo }}
        working_directory: template-repo

    - name: Clone template repository as mirror
      command:
        cmd: 'git -c "http.extraHeader={{ template_auth_header }}" clone --mirror {{ template_repository_url }} {{ working_directory }}'

    - name: Set target repo url
      command:
        cmd: git remote set-url --push origin {{ target_repository_url }}
        chdir: '{{ working_directory }}'

    - name: Fetch the origin repo
      command:
        cmd: git -c "http.extraHeader={{ template_auth_header }}" fetch -p origin
        chdir: '{{ working_directory }}'

    - name: Push repository files
      command:
        # cmd: git -c "http.extraHeader={{ demo_auth_header }}" push --mirror
        cmd: git -c "http.extraHeader={{ demo_auth_header }}" push main
        chdir: '{{ working_directory }}'

    - name: Invoke Issue creation workflow
      uri:
        url: https://api.github.com/repos/{{ context.github_context.target_repository.owner }}/{{ context.github_context.target_repository.repo }}/actions/workflows/initialize.yml/dispatches
        method: POST
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_demo_token }}
        body_format: json
        body:
          ref: "main"
        status_code: 204
